import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';

import { Booking } from '../entities/booking.entity';
import { FlightOfferSnapshot } from '../entities/flight-offer-snapshot.entity';
import { Passenger } from '../entities/passenger.entity';
import { Document } from '../entities/document.entity';

/**
 * Renders a plain itinerary/e-ticket PDF from data already confirmed with
 * Duffel. Duffel's API only ever returns a ticket *number* per passenger
 * (documents.unique_identifier), never a ticket PDF itself, so this is our
 * own rendering rather than a pass-through of a supplier-provided file.
 */
@Injectable()
export class TicketPdfService {
  async generate(
    booking: Booking,
    snapshot: FlightOfferSnapshot | null,
    passengers: Passenger[],
    documents: Document[],
  ): Promise<Buffer> {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    const done = new Promise<Buffer>((resolve, reject) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
    });

    doc.fontSize(20).text('سفريات — تذكرة السفر الإلكترونية', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor('#555').text('Safariyat E-Ticket / Itinerary Receipt', {
      align: 'center',
    });
    doc.moveDown(1.5);

    doc.fillColor('#000').fontSize(11);
    doc.text(`Booking reference (PNR): ${booking.bookingReference ?? 'N/A'}`);
    doc.text(`Booking ID: ${booking.id}`);
    doc.text(`Status: ${booking.status}`);
    doc.moveDown(1);

    if (snapshot) {
      doc.fontSize(14).text('Flight itinerary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);

      snapshot.slices.forEach((slice, idx) => {
        doc.font('Helvetica-Bold').text(`${idx === 0 ? 'Outbound' : 'Return'}: ${slice.origin} → ${slice.destination}`);
        doc.font('Helvetica');
        slice.segments.forEach((seg) => {
          doc.text(
            `  ${seg.marketingCarrier} ${seg.flightNumber} — ` +
              `Departs ${seg.originTerminal ? `Terminal ${seg.originTerminal}, ` : ''}` +
              `${seg.departingAtLocal.toISOString().slice(0, 16).replace('T', ' ')} → ` +
              `Arrives ${seg.destinationTerminal ? `Terminal ${seg.destinationTerminal}, ` : ''}` +
              `${seg.arrivingAtLocal.toISOString().slice(0, 16).replace('T', ' ')}`,
          );
        });
        doc.moveDown(0.5);
      });
      doc.moveDown(0.5);
    }

    doc.fontSize(14).text('Passengers', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11);
    for (const p of passengers) {
      const ticket = documents.find((d) =>
        d.supplierPassengerIds?.includes(p.supplierPassengerId ?? ''),
      );
      doc.text(
        `${p.title.toUpperCase()} ${p.givenName} ${p.familyName}` +
          (ticket ? ` — Ticket No. ${ticket.uniqueIdentifier}` : ''),
      );
    }
    doc.moveDown(1);

    doc.fontSize(9).fillColor('#888').text(
      'This document is an itinerary receipt generated by Safariyat and does not replace any airline-issued travel document requirements.',
      { align: 'center' },
    );

    doc.end();
    return done;
  }
}
